const food = [
  { swahili: "Chakula / vyakula ", english: "Food" },
  { swahili: "Mboga ", english: "Vegetable / vegetables" },
  { swahili: "Dengu  ", english: "Mung bean / lentils" },
  { swahili: "Jibini / jibini ", english: "Cheese / cheeses" },
  { swahili: "Kabeji / kabeji / kabichi ", english: "Cabbage / cabbages" },
  { swahili: "Kiazi / viazi ", english: "Potato / potatoes" },
  {
    swahili: "Maharagwe / mandondo maharagwe / mandondo ",
    english: "Bean / beans",
  },
  { swahili: "Mahindi ", english: "Maize / corn" },
  { swahili: "Mahindi ya kuchoma / mbaazi", english: "Roasted maize / corn" },
  { swahili: "Mchele ", english: "Uncooked rice" },
  { swahili: "Wali ", english: "Cooked rice" },
  { swahili: "Mchicha / michicha ", english: "Spinach / spinaches" },
  { swahili: "Mchuzi / michuzi ", english: "Soup / soups" },
  { swahili: "Muhogo / mihogo ", english: "Cassava / cassavas" },
  { swahili: "Nyama", english: "Meat / meats" },
  { swahili: "Nyama ya kondoo ", english: "Mutton" },
  { swahili: "Nyama ya kuku ", english: "Chicken meat" },
  { swahili: "Nyama ya mbuzi ", english: "Goat meat" },
  { swahili: "Nyama ya ng'ombe ", english: "Beef" },
  { swahili: "Nyama ya nguruwe ", english: "Pork" },
  { swahili: "Nyama ya kuchoma ", english: "Roasted / grilled meat" },
  { swahili: "Kuku", english: "Chicken" },
  { swahili: "Samaki ", english: "Fish" },
  { swahili: "Pilipili ", english: "Pepper" },
  { swahili: "Pilipili hoho ", english: "Chili pepper" },
  { swahili: "Pilipili manga ", english: "Black pepper" },
  { swahili: "Pilipili saumu ", english: "Pepper garlic" },
  { swahili: "Pilipili kichaa ", english: "Hot pepper" },
  { swahili: "Siagi ", english: "Butter" },
  { swahili: "Sukuma wiki ", english: "Collard greens" },
  { swahili: "Unga ", english: "Flour" },
  { swahili: "Unga wa mahindi ", english: "Corn flour" },
  { swahili: "Unga wa ngano ", english: "Wheat flour" },
  { swahili: "Yai / mayai ", english: "Egg / eggs" },
  { swahili: "Vitafunio / karanga ", english: "Snacks" },
  { swahili: "Mkate / mikate ", english: "Bread / breads" },
  { swahili: "Mandazi / mandazi ", english: "Bun / buns" },
  { swahili: "Sandwichi", english: "Sandwich" },
  { swahili: "Kimanda", english: "Toast" },
  { swahili: "Chapati / chapati ", english: "Indian flat bread" },
  { swahili: "Ugali / sima ", english: "Stiff cornmeal porridge" },
  { swahili: "Njugu", english: "Groundnut / peanuts" },
  { swahili: "Karoti ", english: "Carrot / carrots" },
  { swahili: "Kisamvu ", english: "Cassava leaves" },
  { swahili: "Figo ", english: "Kidney / kidneys" },
  { swahili: "Maini ", english: "Liver / livers" },
  { swahili: "Matumbo ", english: "Intestine / intestines / tripe" },
  { swahili: "Mbatata ", english: "Irish potatoes" },
  {
    swahili: "Biringani / biringanya mabiringani ",
    english: "Eggplant / eggplants",
  },
];

export function getFood() {
  return food;
}
